add tracker
my-dungeon-buddy/monorepo pull request #4
Opened 2023-05-16 17:48 UTC by jsankare

basic form layout

2023-05-18 10:55 UTC, jsankare commented
Form logic is working

2023-05-18 13:19 UTC, vmonjaret requested changes

2023-05-18 13:19 UTC, vmonjaret commented on apps/frontend/src/components/TrackerForm/index.tsx
> +  background-color: ${colors["primary-100"]};
I added themes to Styled you can use following
```suggestion
  background-color: ${props => props.theme.colors.primary['100']};
```

2023-05-18 13:19 UTC, vmonjaret commented on apps/frontend/src/components/TrackerForm/index.tsx
> +        ))}
- Should not be within `<form>`

2023-05-18 14:23 UTC, vmonjaret commented
Button to remove one participant is missing

2023-05-18 18:13 UTC, jsankare commented on apps/frontend/src/components/TrackerForm/index.tsx
> +  background-color: ${colors["primary-100"]};
works well

2023-05-18 21:11 UTC, vmonjaret requested changes

2023-05-18 21:11 UTC, vmonjaret commented on apps/frontend/src/components/TrackerForm/index.tsx
> +            <FontAwesomeIcon icon={faTrashCan} />
Use icon from Feather using `react-icons` library

2023-05-18 21:11 UTC, vmonjaret commented on apps/frontend/src/components/colors.ts
> +}
remove this file, if you need to add colors add them in `src/theme.ts` for the values and `theme.d.ts` for the structure

2023-05-18 21:11 UTC, vmonjaret commented on apps/frontend/src/components/TrackerForm/index.tsx
> +          <Submit type="submit">+ Ajouter</Submit>
Use an icon for the `+`

2023-05-18 21:11 UTC, vmonjaret commented on apps/frontend/src/components/TrackerForm/index.tsx
> +  const handleFormSubmit = (event: React.FormEvent<HTMLFormElement>) => {
To handle form take a look at `react-hook-form` (optional, can be a refactor for later)

2023-05-20 09:43 UTC, vmonjaret requested changes

2023-05-20 09:43 UTC, vmonjaret commented on apps/frontend/src/components/TrackerForm/index.tsx
> +            </Row>
Should be is own component

2023-05-20 09:43 UTC, vmonjaret commented on apps/frontend/src/components/TrackerForm/index.tsx
> +      </form>
Keep only that in this component

2023-05-20 09:43 UTC, vmonjaret commented on apps/frontend/src/pages/Home.tsx
> +    <TrackerForm/>
Create a new page `BattleTracker` calling the previous components

2023-05-22 13:03 UTC, vmonjaret commented on apps/frontend/src/components/TrackerForm/index.tsx
> +    const updatedRows = rows.filter((_, i) => i !== index);
instead of using index you can generate an uuid on `handleFormSubmit` and use this uuid in the `handleDeleteRow`

2023-10-15 13:39 UTC, merged